services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: fable
      POSTGRES_USER: fable
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - fable_pg_data:/var/lib/postgresql/data

  fable-service:
    build: .
    ports:
      - "8888:8888"
    environment:
      - PROFILE=prod
    depends_on:
      - postgres

volumes:
  fable_pg_data:
